### ISSUE TITLE
More functions?

### ISSUE THREAD

**Issue by kumar10725** [sparkfun/Qwiic_TCA9548A_Py#1]
Except enable and disable channels functions, no other functions are implemented. 
Example on how to read sensor data from connected modules would be highly appreciated.

**Comment by santaimpersonator** [comment]
Closing as this is not an issue with the python package code. All this package does is open or close the I2C communication lines to the available channels. To pull data from another device, you will need to refer to that device's documentation for information on how to request data from that device.

For more information, please refer to the available documentation for this Python package and the associated product:
https://qwiic-tca9548a-py.readthedocs.io/en/latest/apiref.html
https://learn.sparkfun.com/tutorials/qwiic-mux-hookup-guide
