### ISSUE TITLE
Syntax error in example code

### ISSUE THREAD

**Issue by kz-sam** [sparkfun/Qwiic_TCA9548A_Py#2]
I tried to use the example code provided in the readme and found a few errors/ issues:

1. on line 10: `test.isConnected()` should be `test.is_connected()` 
2. There is no main statement, so if you try to run the example as is, nothing happens. I added a simple:
`if __name__=="__main__":
    runExample()`
to solve this. 

Other than that, it works as expected - Thank you!

**Comment by santaimpersonator** [comment]
Ahh, yup... that was a copy/paste mistake. Fixed.

Closing issue.
